app/home/forms.py
# _*_ coding:utf-8 _*_
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class SuggetionForm(FlaskForm):
    '''
    意见和建议
    '''
    name = StringField(
        label = '邮箱',
        validators=[
            DataRequired('邮箱不能为空！')
        ],
        description='邮箱',
        render_kw={
            'type':'email',
            'placeholder':'请输入邮箱',
            'class':'form-control'
        }
    )
    content = TextAreaField(
        label='意见建议',
        validators=[
            DataRequired('内容不能为空!')
        ],
        description='意见建议',
        render_kw={
            'class':'form-control',
            'placeholder':'请输入内容！',
            'rows':7
        }
    )
    submit = SubmitField(
        '发送消息',
        render_kw={
            'class':'btn-default btn-cf-submit',
        }
    )

app/home/__init__.py
# _*_ coding:utf-8 _*_
from flask import Blueprint

home = Blueprint('home', __name__)

import app.home.views

app/home/views.py
# _*_ coding:utf-8 _*_
from urllib.parse import urlparse, urljoin

from flask import render_template, request, session, redirect, url_for

from app import db
from app.home import home
from app.models import Goods, Cart, Orders, OrdersDetail
from app.utils.decorater import user_login
from app.utils.urlforback import redirect_back


@home.route('/')
def index():
    '''首页'''
    #获得两个热门商品
    hot_goods = Goods.query.order_by(Goods.views_count.desc()).limit(2).all()  #过滤条件后查询新结果后全部取出
    # 获得12个新品
    new_goods = Goods.query.filter_by(is_new=1).order_by(Goods.addtime.desc()).limit(12).all()
    # 获得12个打折商品
    sale_goods = Goods.query.filter_by(is_sale=1).order_by(Goods.addtime.desc()).limit(12).all()
    return render_template('home/index.html', hot_goods=hot_goods, new_goods=new_goods, sale_goods=sale_goods)

@home.route('/goods_list/<int:supercat_id>')
def goods_list(supercat_id=None):
    '''
    商品页
    :param supercat_id: 为大商品分类ID
    :return:
    '''
    page = request.args.get('page', 1, type=int)  #获取page参数值  设置page参数
    page_data = Goods.query.filter_by(supercat_id=supercat_id).paginate(page=page, per_page=12)
    # 左侧边栏热门商品
    hot_goods = Goods.query.filter_by(supercat_id=supercat_id).order_by(Goods.views_count.desc()).limit(7).all()
    return render_template('home/goods_list.html', page_data=page_data, hot_goods=hot_goods, supercat_id=supercat_id)

@home.route('/goods_detail/<int:id>/')
def goods_detail(id=None):
    '''
    详情页
    :param id: 商品ID
    :return:
    '''
    user_id = session.get('user_id', 0)  # 获取用户名ID， 判断用户名是否登陆
    # print('------->', id)
    goods = Goods.query.get_or_404(id) # 根据商品id获取商品数据，如果不存在就返回404 ---> manage.py 中定义的404
    #如果找到， 浏览量+1
    goods.views_count += 1
    db.session.add(goods)  # 添加数据
    db.session.commit() # 提交数据
    #左侧当前小分类热门商品
    hot_goods = Goods.query.filter_by(subcat_id=goods.subcat_id).order_by(Goods.views_count.desc()).limit(5).all()
    # 底部相关小分类热门商品
    similar_goods = Goods.query.filter_by(subcat_id=goods.subcat_id).order_by(Goods.addtime.desc()).limit(5).all()
    return render_template('home/goods_detail.html', goods = goods, hot_goods=hot_goods, similar_goods=similar_goods, user_id=user_id)

@home.route('/search/')
def goods_search():
    '''搜索功能'''
    page = request.args.get('page', 1, type=int) # 获取page参数值 设置参数
    keywords = request.args.get('keywords','',type=str) #获取get请求携带参数 搜索关键字
    if keywords:
        # 使用like实现模糊查询
        page_data = Goods.query.filter(Goods.name.like('%'+keywords+'%')).order_by(Goods.addtime.desc()).paginate(page=page, per_page=12) #有就显示最新12条
    else:
        page_data = Goods.query.order_by(Goods.addtime.desc()).paginate(page=page, per_page=12)

    hot_goods = Goods.query.order_by(Goods.views_count.desc()).limit(7).all()
    return render_template('home/goods_search.html', page_data=page_data, keywords=keywords, hot_goods=hot_goods)

@home.route('/cart_add/')
@user_login
def cart_add():
    '''
    添加商品到购物车 这里需要判断是否登陆了
    :return:
    '''
    cart = Cart(
        goods_id = request.args.get('goods_id'),
        number = request.args.get('number'),
        user_id = session.get('user_id', 0) # 获取用户ID,判断用户是否登录
    )
    db.session.add(cart) # 添加数据
    db.session.commit() # 提交数据
    return redirect_back()
    # return redirect(url_for(next=request.url))

@home.route('/cart_clear/')
@user_login
def cart_clear():
    ''' 清空购物车
    '''
    user_id = session.get('user_id', 0)
    Cart.query.filter_by(user_id=user_id).update({'user_id':0})
    db.session.commit()
    return redirect(url_for('home.shopping_cart'))

@home.route('/shopping_cart/')
@user_login
def shopping_cart():
    user_id = session.get('user_id', 0)
    cart = Cart.query.filter_by(user_id=user_id).order_by(Cart.addtime.desc()).all()
    if cart:
        return render_template('home/shopping_cart.html', cart=cart)
    else:
        return render_template('home/empty_cart.html')



@home.route('/cart_order/', methods=['GET', 'POST'])
@user_login
def cart_order():
    if request.method == 'POST':
        user_id = session.get('user_id', 0)
        # 添加订单
        orders = Orders(
            user_id = user_id,
            recevie_name = request.form.get('recevie_name'),
            recevie_tel = request.form.get('recevie_tel'),
            recevie_address = request.form.get('recevie_address'),
            remark = request.form.get('remark')
        )
        db.session.add(orders)
        db.session.commit()
        # 添加订单详情
        cart = Cart.query.filter_by(user_id=user_id).all()
        object = []
        for item in cart:
            object.append(
                OrdersDetail(
                    order_id = orders.id,
                    goods_id = item.goods_id,
                    number = item.number,
                )
            )
        db.session.add_all(object)
        # 修改购物车状态
        Cart.query.filter_by(user_id=user_id).update({'user_id':0})
        db.session.commit()
    return redirect(url_for('home.index'))

app/templates/home/empty_cart.html
{% extends "common/common.html" %}
{% block content %}
	<!-- //网站头部 -->
    <div id="mr-mainbody" class="container mr-mainbody">
        <div class="row">
            <!-- 页面主体内容 -->
            <div id="mr-content" class="mr-content col-xs-12">
                <div id="mrshop" class="mrshop common-home">
                    <div class="container_oc">
                        <div class="container_oc">
                            <div class="breadcrumb"></div>
                        </div>
                        <div class="row">
                            <div id="content_oc" class="col-sm-12" style="min-height:300px;">
                                <h1>我的购物车</h1>
                                <div class="table-responsive cart-info" style="margin-bottom:50px;">您的购物车为空！</div>
                                <div class="buttons">
                                    <div class="pull-left">
                                        <a href="{{url_for('home.index')}}" class="btn btn-primary btn-default">继续购物</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- //页面主体内容 -->
        </div>
    </div>
{% endblock %}

app/templates/home/goods_list.html
{% extends "common/common.html" %}
{% block content %}
	<div id="mr-mainbody" class="container mr-mainbody">
		<div class="row">
			<!-- //分页显示图书列表 -->
			<div id="mr-content"
				class="mr-content col-xs-12 col-sm-12 col-md-9 col-md-push-3">
				<div id="system-message-container" style="display: none;"></div>
				<div id="mrshop" class="mrshop common-home">
					<div class="container_oc">
						<ul class="breadcrumb">
						</ul>
						<div class="row">
							<div id="content_oc" class="col-sm-12">
								<div class="box_oc">
									<div class="box-content">
										<hr>
										<div class="row">
											{% for item in page_data.items %}
											<div class="product-layout product-grid col-lg-3 col-md-3 col-sm-6 col-xs-12">
												<div class="product-thumb">
													<div class="actions">
														<div class="image">
															<a style="width: 95%" href="/goods_detail/{{item.id}}?type={{item.supercat_id}}">
																<img src="{{url_for('static',filename='images/goods/'+item.picture)}}"
																class="img-responsive"> </a>
														</div>
														<div class="button-group btn-grid">
															<div class="cart">
																<button class="btn btn-primary btn-primary"
																	type="button" data-toggle="tooltip"
																	onclick='javascript:window.location.href="/cart_add/?goods_id={{item.id}}&number=1";alert("添加成功，请继续购物") '
																	style="display: none; width: 33.3333%;"
																	data-original-title="添加到购物车">
																	<i class="fa fa-shopping-cart"></i>
																</button>
															</div>
															<div class="wishlist">
																<button class="btn" type="button" data-toggle="tooltip"
																	title="收藏">
																	<i class="fa fa-heart"></i>
																</button>
															</div>
														</div>
													</div>
													<div>
														<div class="caption">
															<div class="name">
																<a href="/goods_detail/{{item.id}}?type={{item.supercat_id}}" style="width: 95%">
																	<span style="color: #0885B1">名称：</span>{{item.name}}</a>
															</div>

															<p class="price">
																<span class="price-new">分类：</span> <span>{{item.subcat.cat_name}}</span>
																<span class="price-tax">价格: {{item.current_price}}元
																</span>
															</p>
														</div>

													</div>
												</div>
											</div>
											{% endfor %}
										</div>
										<div class="row pagination">
											<table width="100%" border="0" cellspacing="0" cellpadding="0">
												<tr>
												  <td height="30" align="right">当前页数：[{{page_data.page}}/{{page_data.pages}}]&nbsp;
													<a href="{{ url_for('home.goods_list',page=1,supercat_id=supercat_id) }}">第一页</a>
													{% if page_data.has_prev %}
													  <a href="{{ url_for('home.goods_list',page=page_data.prev_num,supercat_id=supercat_id) }}">上一页</a>
													{% endif %}
													{% if page_data.has_next %}
												　     <a href="{{ url_for('home.goods_list',page=page_data.next_num,supercat_id=supercat_id) }}">下一页</a>
													{% endif %}　
													<a href="{{ url_for('home.goods_list',page=page_data.pages,supercat_id=supercat_id) }}">最后一页&nbsp;</a>
												  </td>
												</tr>
											</table>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- //分页显示图书列表 -->
			<!-- 显示左侧热门商品 -->
		<div class="mr-sidebar mr-sidebar-left col-xs-12 col-sm-4 col-sm-pull-8 col-md-3 col-md-pull-9  hidden-sm hidden-xs">
			<div class="mr-module module " id="Mod157">
				<div class="module-inner">
					<h3 class="module-title ">
						<span>热门商品</span>
					</h3>
					<div class="module-ct">
						<div class="mrshop">
							<div class="container_oc">
								<div class="box_oc">
									<div>
										<div class="box-product product-grid">
											{% for item in hot_goods %}
											<div>
												<div class="image">
													<a href="/goods_detail/{{item.id}}?type={{item.supercat_id}}">
														<img src="{{url_for('static',filename='images/goods/'+item.picture)}}" width="80px">
													</a>
												</div>
												<div class="name">
													<a href="/goods_detail/{{item.id}}?type={{item.supercat_id}}"> {{item.name}}</a>
												</div>
												<div class="rating">
													<span class="fa fa-stack"><i
														class="fa fa-star fa-stack-2x"></i><i
														class="fa fa-star-o fa-stack-2x"></i></span> <span
														class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i
														class="fa fa-star-o fa-stack-2x"></i></span> <span
														class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i
														class="fa fa-star-o fa-stack-2x"></i></span> <span
														class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i
														class="fa fa-star-o fa-stack-2x"></i></span> <span
														class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i
														class="fa fa-star-o fa-stack-2x"></i></span>
												</div>
												<div class="price">{{item.current_price}}元</div>
											</div>
											{% endfor %}
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
			<!-- // 显示左侧热门商品 -->
		</div>
	</div>
	<!-- 版权栏 -->

{% endblock %}

app/templates/home/shopping_cart.html
{% extends "common/common.html" %}
{% block content %}
	<!-- //网站头部 -->
    <div id="mr-mainbody" class="container mr-mainbody">
        <div class="row">
            <!-- 页面主体内容 -->
            <div id="mr-content" class="mr-content col-xs-12">
                <div id="mrshop" class="mrshop common-home">
                    <div class="container_oc">
                        <div class="row">
                            <div  class="col-sm-12">
                                <h1>我的购物车</h1>
                                <!-- 显示购物车中的商品 -->
                                <div class="table-responsive cart-info">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <td class="text-center image">商品图片</td>
                                                <td class="text-left name">商品名称</td>
                                                <td class="text-left quantity">数量</td>
                                                <td class="text-right price">单价</td>
                                                <td class="text-right">总计</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <!-- 遍历购物车中的商品并显示 -->
                                            {% for item in cart %}
                                             <tr>
                                                <td class="text-center image" width="20%">
                                                    <a href="{{url_for('home.goods_detail',id=item.goods.id)}}">
                                                    <img width="80px" src="{{url_for('static',filename='images/goods/'+item.goods.picture)}}"> </a>
                                                </td>
                                                <td class="text-left name">
                                                    <a href="{{url_for('home.goods_detail',id=item.goods.id)}}">{{item.goods.name}}</a>
                                                </td>
                                                <td class="text-left quantity">{{item.number}}件</td>
                                                <td class="text-right price">{{item.goods.current_price}}元</td>
                                                <td class="text-right total" value="{{item.goods.current_price * item.number}}">
                                                    {{item.goods.current_price * item.number}}元
                                                </td>
                                            </tr>
                                            {% endfor %}
                                            <!-- //遍历购物车中的商品并显示 -->
                                        </tbody>
                                    </table>
                                </div>
                                <!-- //显示购物车中的商品 -->
                                <!-- 显示总计金额  -->
                                <div class="row cart-total">
                                    <div class="col-sm-4 col-sm-offset-8">
                                        <table class="table table-bordered">
                                            <tbody>
                                                <tr >
                                                <span>
                                                    <strong>总计:</strong>
                                                    <p id="total_price"></p>
                                                </span>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <!-- //显示总计金额  -->
                            </div>
                        </div>
                        <!-- 填写物流信息 -->
                        <div class="row">
                            <div id="content_oc" class="col-sm-12">
                                <h1>物流信息</h1>
                                <!-- 填写物流信息的表单 -->
                                <form action="{{url_for('home.cart_order')}}" method="post" id="myform">
                                    <div class="table-responsive cart-info">
                                        <table class="table table-bordered">
                                            <tbody>
                                                <tr>
                                                    <td class="text-right" width="20%">收货人姓名：</td>
                                                    <td class="text-left quantity">
                                                        <div class="input-group btn-block" style="max-width: 400px;">
                                                            <input type="text" id="recevieName" name="recevie_name" size="10" class="form-control">
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="text-right">收货人手机：</td>
                                                    <td class="text-left quantity">
                                                        <div class="input-group btn-block" style="max-width: 400px;">
                                                            <input type="text" id="tel" name="recevie_tel" size="10" class="form-control">
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="text-right">收货人地址：</td>
                                                    <td class="text-left quantity">
                                                        <div class="input-group btn-block" style="max-width: 400px;">
                                                            <input type="text" id="address" name="recevie_address" size="1" class="form-control">
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="text-right">备注：</td>
                                                    <td class="text-left quantity">
                                                        <div class="input-group btn-block" style="max-width: 400px;">
                                                            <input type="text" name="remark" size="1" class="form-control">
                                                        </div>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </form>
                                <!-- //填写物流信息的表单 -->
                            </div>
                        </div>
                        <!-- //填写物流信息 -->
                        <br />
                        <!-- 显示支付方式 -->
                        <div class="row">
                            <div id="content_oc" class="col-sm-12">
                                <h1>支付方式</h1>
                                <div class="table-responsive cart-info">
                                    <table class="table table-bordered">
                                        <tbody>
                                            <tr>
                                                <td class="text-left"><img src="{{url_for('static',filename='home/images/zhifubao.png')}}" /></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <br /> <br />
                                <div class="buttons">
                                    <div class="pull-left">
                                        <a href="{{url_for('home.index')}}" class="btn btn-primary btn-default">继续购物</a>
                                    </div>
                                    <div class="pull-left">
                                        <a href="{{url_for('home.cart_clear')}}" class="btn btn-primary btn-default">清空购物车</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="javascript:zhifu();" class="tigger btn btn-primary btn-primary">结账</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- //显示支付方式 -->
                    </div>
                </div>
            </div>
            <!-- //页面主体内容 -->
        </div>
    </div>
    <!-- 使用jBox插件实现一个支付对话框 -->
    <script type="text/javascript" src="{{url_for('static',filename='home/js/jBox/jquery-1.4.2.min.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static',filename='home/js/jBox/jquery.jBox-2.3.min.js')}}"></script>
    <link type="text/css" rel="stylesheet" href="{{url_for('static',filename='home/js/jBox/Skins2/Pink/jbox.css')}}" />
    <script type="text/javascript">
        // 获取总额
        $(document).ready(function(){
            var total_price = 0
            $('.total').each(function(){
                total_price += parseFloat($(this).attr('value'))
            })
            $('#total_price').text(total_price+"元")
        });
        function zhifu() {
            //验证收货人姓名
            if ($('#recevieName').val() === "") {
                alert('收货人姓名不能为空！');
                return;
            }
            //验证收货人手机
            if ($('#tel').val() === "") {
                alert('收货人手机不能为空！');
                return;
            }
            //验证手机号是否合法
            if (isNaN($('#tel').val())) {
                alert("手机号请输入数字");
                return;
            }
            //验证收货人地址
            if ($('#address').val() === "") {
                alert('收货人地址不能为空！');
                return;
            }
            //设置对话框中要显示的内容
            var html = '<div class="popup_cont">'
                    + '<div style="width: 256px; height: 250px; text-align: center; margin:70px" >'
                    + '<image src="/static/home/images/qr.png" width="256" height="256" />'
                    + '<p style="color:red;padding-tope:30px">该页面仅为测试页面，并未实现支付功能</p></div>'
                    + '</div>';
            var content = {
                state1 : {
                    content : html,
                    buttons : {
                        '取消' : 0,
                        '支付' : 1
                    },
                    buttonsFocus : 0,
                    submit : function(v, h, f) {
                        if (v == 0) {//取消按钮的响应事件
                            return true; //关闭窗口
                        }
                        if (v == 1) {//支付按钮的响应事件
                            document.getElementById('myform').submit();//提交表单
                            return true;
                        }
                        return false;
                    }
                }
            };
            $.jBox.open(content, '支付', 400, 450);//打开支付窗口
        }
    </script>
    <!-- // 使用jBox插件实现一个支付对话框 -->

{% endblock %}