app/users/forms.py
# _*_ coding:utf-8 _*_
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Regexp, EqualTo, ValidationError, Length, Email, email_validator
from app.models import User
import email_validator

class RegisterForm(FlaskForm):
    """
    用户注册表单
    """
    username = StringField(
        label='账户：',
        validators=[
            DataRequired('用户名不能为空！'),
            Length(min=3, max=50, message='用户名长度必须在3-10位之间')
        ],
        # css 渲染
        description='用户名',
        render_kw={
            'type':'text',
            'placeholder':'请输入用户名',
            'class':'validate-username',
            'size':38
        }
    )
    phone = StringField(
        label='联系电话：',
        validators=[
            DataRequired('手机号不能为空！'),
            Regexp('1[2345678][0-9]{9}',message='手机号码格式不正确')
        ],
        description='手机号',
        render_kw={
            'type':'text',
            'placeholder':'请输入联系电话',
            'size':38
        }
    )
    email = StringField(
        label="邮箱 ：",
        validators=[
            DataRequired("邮箱不能为空！"),
            Email("邮箱格式不正确！")
        ],
        description="邮箱",
        render_kw={
            "type": "email",
            "placeholder": "请输入邮箱！",
            "size": 38,
        }
    )
    password = PasswordField(
        label='密码：',
        validators=[
            DataRequired('密码不能为空！')
        ],
        description='密码',
        render_kw={
            'placeholder':'请输入密码！',
            'size':38
        }
    )
    repassword = PasswordField(
        label='确认密码：',
        validators=[
            DataRequired('请输入密码！'),
            EqualTo('password', message='两次密码不一致！')
        ],
        description='确认密码',
        render_kw={
            'placeholder':'请输入确认密码！',
            'size':38
        }
    )
    submit = SubmitField(
        '同一协议定注册',
        render_kw={
            'class':'btn btn-primary login',
        }
    )

    #wtfform 没有到数据库查重邮箱和电话的配置，只有用户名的，所以使用自定义校验规则 vilidate_变量名
    def vilidate_email(self, field):
        '''
        检测注册邮箱是否已经存在
        :param field: 字段名
        '''
        email = field.data
        user = User.query.filter_by(email=email).count()
        if user == 1:
            raise ValidationError('邮箱已经存在！') #抛出异常

    def vilidate_phone(self, field):
        '''
        检测注册手机是否已经存在
        :param field: 字段名
        '''
        phone = field.data
        user = User.query.filter_by(phone=phone).count()
        if user == 1:
            raise ValidationError('手机号已经存在！')

class LoginForm(FlaskForm):
    '''
    登陆功能
    '''
    username = StringField(
        validators=[
            DataRequired('用户名不能为空！'),
            Length(min=3, max=50, message='用户名长度必须在3-10位之间')
        ],
        description='用户名',
        render_kw={
            'type':'text',
            'placeholder':'请输入用户名',
            'class':'validate-username',
            'size':'38',
            'maxlength':99
        }
    )
    password = PasswordField(
        validators=[
            DataRequired('密码不能为空！'),
            Length(min=3,message='密码长度不少于6位')
        ],
        description='密码',
        render_kw={
            'type':'password',
            'placeholder':'请输入密码！',
            'size':38,
            'maxlength':99
        }
    )
    verify_code = StringField(
        'VerifyCode',
        validators=[DataRequired()],
        render_kw={
            'class':'validate-code',  # flask里边封装了可以验证的函数
            'size':18,
            'maxlength':4,
        }
    )
    submit = SubmitField(
        '登陆',
        render_kw={
            'class': 'btn btn-primary login'
        }
    )

class PasswordForm(FlaskForm):
    '''
    修改密码表单
    '''
    old_password = PasswordField(
        label='原始密码：',
        validators=[
            DataRequired('原始密码不能为空!')
        ],
        description='原始密码',
        render_kw={
            'placeholder':'请输入原始密码',
            'size':38
        }
    )
    password = PasswordField(
        label='新密码：',
        validators=[
            DataRequired('新密码不能为空!')
        ],
        description='新密码',
        render_kw={
            'placeholder':'请输入新密码',
            'size':38,
        }
    )
    repassword = PasswordField(
        label='确认密码：',
        validators=[
            DataRequired('请输入确认密码'),
            EqualTo('password', message='两次密码不一致!')
        ],
        description='确认密码',
        render_kw={
            'placeholder':'请输入确认密码！',
            'size':38
        }
    )
    submit = SubmitField(
        '确认修改',
        render_kw={
            "class": "btn btn-primary login",
        }
    )
    # 自定义校验
    # 提交按钮后  自动触发旧密码校验如果通过才返回True
    def validate_old_password(self, field):
        from flask import session
        old_password = field.data
        user_id = session['user_id']
        user = User.query.get(int(user_id)) # 拿到user_id这条数据
        if not user.check_password(old_password):
            raise ValidationError('原始密码错误！')

app/users/__init__.py
# _*_ coding:utf-8 _*_

from flask import Blueprint

user = Blueprint('user', __name__)

import app.users.views

app/users/views.py
# _*_ coding:utf-8 _*_
from io import BytesIO

from flask import make_response, session, redirect, url_for, render_template, flash, request
from werkzeug.security import generate_password_hash

from app.utils.verifycode import get_verify_code
from . import user
from .forms import RegisterForm, LoginForm, PasswordForm
from .. import db
from ..models import User
from ..utils.decorater import user_login


@user.route('/register/', methods=['GET', 'POST'])
def register():
    '''
    注册功能
    '''
    if 'user_id' in session:
        return redirect(url_for('home.index'))
    form = RegisterForm()
    if form.validate_on_submit(): # ---> if post and dalidate
        data = form.data
        # 为User类属性赋值
        user = User(
            username = data['username'],
            email = data['email'],
            password = generate_password_hash(data['password']), # 对密码加密
            phone = data['phone']
        )
        db.session.add(user) # 添加数据
        db.session.commit() # 提交数据
        return redirect(url_for('user.register')) #登陆成功，跳转到登陆界面  之后变成 register
    return render_template('users/register.html', form=form) # 渲染模板

@user.route('/code')
def get_code():
    image, code = get_verify_code()
    #图片以而兼职形式写入
    buf = BytesIO()
    image.save(buf, 'jpeg')
    buf_str = buf.getvalue()
    # 把已经转换成而兼职的buf_str 作为response返回前端， 并设置首部字段
    response = make_response(buf_str)
    response.headers['Content-type'] = 'image/gif'
    # 将验证码字符串储存在session 中 当提交用户登陆信息后，对比验证码是否合规
    session['image'] = code
    return response

@user.route('/login/', methods=['GET', 'POST'])
def login():
    '''
    登陆
    '''
    if 'user_id' in session:
        # session.pop("user_id", None)
        # session.pop("username", None)
        return redirect(url_for('home.index'))

    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        # 判断验证码
        if session.get('image').lower() != form.verify_code.data.lower():
            flash('验证码错误', 'err')
            return render_template('users/login.html', form=form) #验证码不对 返回登陆界面
        user = User.query.filter_by(username=data['username']).first() # 获取用户信息
        if not user:
            flash('用户名不存在！', 'err')
            return render_template('users/login.html') #返回登陆首页

        if not user.check_password(data['password']):
    # 调用check_password()方法，检测用户名密码是否匹配
            flash('密码错误！', 'err')
            return render_template('users/login.html')
        #如果以上都过了，证明登陆成功了
        session['user_id'] = user.id
        # user_id 写入session， 后面用户判断用户是否登陆
        session['username'] = user.username
        # 将username写入session, 后面做调用
        return redirect(url_for('home.index')) # 登陆成功，跳转到首页
        # return 'ok'
    return render_template('users/login.html', form=form) # form中信息校验不通过， 返回登陆界面


@user.route('/modify_password/', methods=['GET', 'POST'])
@user_login
def modify_password():
    '''修改密码'''
    form = PasswordForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(username=session['username']).first()
        from werkzeug.security import generate_password_hash
        user.password = generate_password_hash(data['password'])
        db.session.add(user)
        db.session.commit()
        return "<script>alert('密码修改成功');location.href='/';</script>" # 跳转回首页
    return render_template('users/modify_password.html', form=form)

@user.route('/logout/')
def logout():
    '''
    退出登陆
    '''
    # 从定向到 user 模块下的登陆
    session.pop('user_id', None)
    session.pop('username', None)
    return redirect(url_for('user.login'))

app/templates/users/login.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<title>登录-kaka商城</title>
<link rel="stylesheet" href="{{url_for('static',filename='home/css/mr-01.css')}}" type="text/css">
</head>
<body>
	<div id="mr-mainbody" class="container mr-mainbody">
		<div class="row">
			<!-- 主体内容 -->
			<div id="mr-content" class="mr-content col-xs-12">
				<div class="login-wrap" style="margin-bottom: 60px; margin-top: 50px">
					<div style="max-width: 540px; margin: 0 auto;">
						<a href="{{url_for('home.index')}}" title="点击返回首页"><img src="{{url_for('static',filename='home/images/logo.png')}}" style="width: 200px; margin-bottom: 5px"></a>
					</div>
					<div class="login">
						<div class="page-header" style="pause: 0px;"> <h1 class="login_h1">会员登录</h1> </div>
						    {% for msg in get_flashed_messages(category_filter=["err"]) %}
								<div style="color:red;text-align:center;font-size:16px">
								  	{{ msg }}
								</div>
							{% endfor %}
						<!-- 会员登录表单 -->
						<form action="" method="post" class="form-horizontal">
							<fieldset>
								<div class="form-group">
									<div class="col-sm-4 control-label">
										<label id="username-lbl" for="username" class="required">账户 ：</label>
									</div>
									<div class="col-sm-8">
										<!-- 账户文本框 -->
										{{form.username}}
										{% for err in form.username.errors %}
										<span class="error">{{ err }}</span>
										{% endfor %}
									</div>
								</div>
								<div class="form-group">
									<div class="col-sm-4 control-label">
										<label id="password" for="password" class="required">密码 ：</label>
									</div>
									<div class="col-sm-8">
										<!-- 密码文本框 -->
										{{form.password}}
									</div>
								</div>
								<div class="form-group">
									<div class="col-sm-4 control-label">
										<label id="password-lbl" for="password" class="required">验证码 ：</label>
									</div>
									<div class="col-sm-8" style="clear: none;">
										<!-- 验证码文本框 -->
										{{form.verify_code}}
											<!-- 显示验证码 -->
											<img class="img_checkcode" src="{{url_for('user.get_code')}}" width="116"
	 											height="43" onclick="this.src='{{url_for('user.get_code')}}'+'?'+ Math.random()">
									</div>
								</div>
								<div class="form-group">
									<div class="col-sm-offset-4 col-sm-8">
										{{form.csrf_token}}
										{{form.submit}}
									</div>
								</div>
								<div class="form-group"
									style="border-top: 1px solid #D9D9D9; margin: 20px;">
									<label
										style="float: right; color: #858585; margin-right: 40px; margin-top: 10px; font-size: 14px;">没有账户？<a
										href="{{url_for('user.register')}}">立即注册</a></label>
								</div>
							</fieldset>
						</form>
					</div>
				</div>
			</div>
			<!-- //主体内容 -->
		</div>
	</div>
</body>
</html>

app/templates/users/modify_password.html
{% extends "common/common.html" %}
{% block content %}
	<!-- //网站头部 -->
	<div id="mr-mainbody" class="container mr-mainbody">
		<div class="row">
			<div id="mr-content" class="mr-content col-xs-12">
				<div class="login-wrap"
					style="margin-bottom: 60px; margin-top: 50px">
					<div class="login">
						<div class="page-header" style="pause: 0px;">
							<h1 class="login_h1">更改密码</h1>
						</div>
						<!-- 会员更改密码表单 -->
						<form  action="" method="post" class="form-horizontal">
							<fieldset>
								<div class="form-group">
									<div class="col-sm-4 control-label">
										{{form.old_password.label}}
									</div>
									<div class="col-sm-8">
										<!-- 密码文本框 -->
										{{form.old_password}}
										{% for err in form.old_password.errors %}
										<span class="error">{{ err }}</span>
										{% endfor %}
									</div>
								</div>
								<div class="form-group">
									<div class="col-sm-4 control-label">
										{{form.password.label}}
									</div>
									<div class="col-sm-8">
										<!-- 密码文本框 -->
										{{form.password}}
										{% for err in form.password.errors %}
										<span class="error">{{ err }}</span>
										{% endfor %}
									</div>
								</div>
								<div class="form-group">
									<div class="col-sm-4 control-label">
										{{form.repassword.label}}
									</div>
									<div class="col-sm-8">
										<!-- 确认密码文本框 -->
										{{form.repassword}}
										{% for err in form.repassword.errors %}
										<span class="error">{{ err }}</span>
										{% endfor %}
									</div>
								</div>
								<div class="form-group">
									<div class="col-sm-offset-4 col-sm-8">
										{{ form.csrf_token }}
										{{ form.submit }}
									</div>
								</div>
							</fieldset>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- //主体内容 -->
{% endblock %}

app/templates/users/register.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>注册-kaka商城</title>
    <link rel="stylesheet" href="{{url_for('static',filename='home/css/mr-01.css')}}" type="text/css">
</head>
<body>
<!-- 主体内容 -->
<div id="mr-mainbody" class="container mr-mainbody">
    <div class="row">
        <div id="mr-content" class="mr-content col-xs-12">
            <div class="login-wrap"
                 style="margin-bottom: 60px; margin-top: 50px">
                <div style="max-width: 540px; margin: 0 auto;">
                    <a href="{{url_for('home.index')}}" title="点击返回首页">
                        <img src="{{url_for('static',filename='home/images/logo.png')}}" style="width: 200px; margin-bottom: 5px"></a>
                </div>
                <div class="login">
                    <div class="page-header" style="pause: 0px;">
                        <h1 class="login_h1">会员注册</h1>
                    </div>
                    <!-- 会员注册表单 -->
                    <form action="" method="post" class="form-horizontal">
                        <fieldset>
                            <div class="form-group">
                                <div class="col-sm-4 control-label">
                                    {{form.username.label}}
                                </div>
                                <div class="col-sm-8">
                                    <!-- 账户文本框 -->
                                    {{form.username}}
                                    {% for err in form.username.errors %}
                                    <span class="error">{{ err }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-4 control-label">
                                    {{form.password.label}}
                                </div>
                                <div class="col-sm-8">
                                    <!-- 密码文本框 -->
                                    {{form.password}}
                                    {% for err in form.password.errors %}
                                    <span class="error">{{ err }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-4 control-label">
                                    {{form.repassword.label}}
                                </div>
                                <div class="col-sm-8">
                                    <!-- 确认密码文本框 -->
                                    {{form.repassword}}
                                    {% for err in form.repassword.errors %}
                                    <span class="error">{{ err }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-4 control-label">
                                    {{form.phone.label}}
                                </div>
                                <div class="col-sm-8" style="clear: none;">
                                    <!-- 输入联系电话的文本框 -->
                                    {{form.phone}}
                                    {% for err in form.phone.errors %}
                                    <span class="error">{{ err }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-4 control-label">
                                    {{form.email.label}}
                                </div>
                                <div class="col-sm-8" style="clear: none;">
                                    <!-- 输入邮箱的文本框 -->
                                    {{form.email}}
                                    {% for err in form.email.errors %}
                                    <span class="error">{{ err }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="form-group">
                                <div style="float: right; padding-right: 216px;">
                                    kaka商城<a href="#" style="color: #0885B1;">《使用条款》</a>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-4 col-sm-8">
                                    {{ form.csrf_token }}
                                    {{ form.submit }}
                                </div>
                            </div>
                            <div class="form-group" style="margin: 20px;">
                                <label
                                        style="float: right; color: #858585; margin-right: 80px; margin-top: 10px; font-size: 14px;">已有账号！<a
                                        href="{{url_for('user.login')}}">去登录</a></label>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- //主体内容 -->
</body>
</html>